(function(){
  const D=(he,en)=>({he,en});
  const modern={win10:'yes',win11:'yes'},from8={win8:'yes',win81:'yes',...modern};
  const cmdDoc=n=>'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/'+n;
  const settings='https://learn.microsoft.com/en-us/windows/apps/develop/launch/launch-settings';
  const sfc='https://support.microsoft.com/en-us/windows/experience/backup-recovery/using-system-file-checker-in-windows';
  const network='https://support.microsoft.com/en-us/windows/experience/connectivity-networking/fix-wi-fi-connection-issues-in-windows';
  const patches=[
    {id:'net-ping',onError:[{when:D('Request timed out / Destination host unreachable','Request timed out / Destination host unreachable'),fix:D('לא התקבלה תשובה לבדיקה. הסיבה יכולה להיות חסימת ICMP, בעיית יעד, תצורה או קישוריות. בדוק את החיבור המקומי והשווה ליעד נוסף לפני איפוס הגדרות.','No reply was received for this check. Possible causes include ICMP filtering, a destination problem, configuration or connectivity. Inspect the local connection and compare another destination before resetting settings.')}],desc:D('בדיקת תגובת ICMP מיעד מסוים; אינה בדיקה מלאה של הגלישה.','Check one destination’s ICMP response; this is not a complete web-connectivity test.'),expectedOk:D('תשובה מעידה שהיעד ענה לבדיקה. היעדר תשובה יכול לנבוע גם מחסימת ICMP; בדוק אתר נוסף ודפדפן לפני הסקת מסקנות.','A reply means that destination answered. No reply can also mean ICMP is blocked; compare another site and browser before drawing conclusions.'),source:cmdDoc('ping')},
    {id:'net-nslookup',expectedOk:D('כתובת בתשובה מעידה שהשרת השיב לשאילתת DNS. אתר עדיין יכול להיכשל מסיבה אחרת; בדוק גם את שם האתר שהוקלד.','An address in the answer means the DNS server answered the query. A website may still fail for another reason; also check the name you entered.'),source:cmdDoc('nslookup')},
    {id:'net-ipconfig',expectedOk:D('מצא את המתאם הפעיל, כתובת IPv4, שער ברירת מחדל ושרתי DNS. כתובת מקומית לבדה אינה הוכחה שיש גישה לאינטרנט.','Find the active adapter, IPv4 address, default gateway and DNS servers. A local address alone does not prove internet access.'),before:D('פלט עשוי לכלול כתובות ושמות רשת. לפני שיתוף צילום, הסתר פרטים שאינם נחוצים לפתרון התקלה.','Output may include addresses and network names. Before sharing a screenshot, hide details that are not needed.'),source:cmdDoc('ipconfig')},
    {id:'disk-chkdsk',title:D('בדיקת מערכת הקבצים (CHKDSK)','Check the file system (CHKDSK)'),desc:D('מתחילים בדוח מצב. תיקון שגיאות וסריקת סקטורים הם פעולות נפרדות.','Start with a status report. Repairing errors and checking sectors are separate operations.'),methods:[{type:'cmd',value:'chkdsk C:',best:true}],before:D('בדוק שהאות C: היא הכונן הרצוי. הפקודה המוצגת אינה מפעילה תיקון. ‎/f משנה את מערכת הקבצים; ‎/r מוסיף בדיקת סקטורים ויכול להימשך זמן רב. בכונן חשוד כתקול, גבה חומר חשוב לפני תיקון.','Check that C: is the intended drive. This displayed command does not request repairs. /f changes the file system; /r adds a sector check and can take a long time. Back up important data before attempting repairs on a suspect drive.'),expectedOk:D('קרא אם דווחו שגיאות. הבדיקה אינה תעודת תקינות לחומרת הדיסק, ובכונן פעיל ייתכנו מגבלות על הדוח.','Read whether errors were reported. This is not a hardware-health certificate, and an active drive can limit the report.'),source:cmdDoc('chkdsk')},
    {id:'diag-sfc',before:D('פתח CMD כמנהל. ב-Windows 10/11, בהליך תיקון קבצי מערכת Microsoft מנחה להפעיל תחילה DISM /RestoreHealth ואז SFC. שמור עבודה פתוחה והמתן לסיום.','Open CMD as administrator. For the Windows 10/11 system-file repair procedure, Microsoft places DISM /RestoreHealth before SFC. Save open work and allow the scan to finish.'),expectedOk:D('התוצאה מפרידה בין: לא נמצאו פגמים, פגמים שתוקנו, או פגמים שלא תוקנו. תוצאה נקייה אינה שוללת תקלה בתוכנה, בדרייבר או בחומרה.','The result distinguishes no corruption, repaired corruption, and unrepaired corruption. A clean result does not rule out an application, driver or hardware fault.'),source:sfc},
    {id:'diag-dism',compat:from8,before:D('דורש הרשאת מנהל. ‎/Online מתייחס ל-Windows שפועל כעת; הוא אינו מבטיח שהפעולה ללא אינטרנט. התיקון עשוי להשתמש ב-Windows Update. אם חסרים קובצי מקור, אל תשתמש ב-ISO אקראי.','Requires administrator rights. /Online means the currently running Windows installation, not that the repair is internet-free. Repair may use Windows Update. Do not supply an arbitrary ISO when source files are missing.'),source:'https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/repair-a-windows-image'},
    {id:'sys-topproc',title:D('זמן מעבד מצטבר של תהליכים','Cumulative process CPU time'),desc:D('ממיין לפי שניות מעבד שנצברו מאז הפעלת כל תהליך — לא לפי אחוז העומס ברגע זה.','Sort by processor seconds accumulated since each process started, not by current CPU percentage.'),expectedOk:D('תהליך ותיק עשוי להיות ראשון גם כשהוא אינו מעמיס עכשיו. לעומס נוכחי פתח את מנהל המשימות.','A long-running process may rank first while idle now. Use Task Manager to inspect current load.'),source:'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process'},
    {id:'sys-winget',title:D('בדיקת עדכוני תוכנות (winget)','Check application updates (winget)'),desc:D('מציג עדכונים מוצעים לפני בחירת התוכנה שרוצים לעדכן.','List available updates before choosing which application to update.'),methods:[{type:'cmd',value:'winget upgrade',best:true}],before:D('דורש App Installer / winget זמין. הפקודה המוצגת רק מציגה רשימה; הוספת ‎--all תעדכן תוכנות ועלולה לדרוש אישורים או לסגור יישומים.','Requires App Installer / winget. This displayed command lists updates; adding --all updates applications and may require prompts or close apps.'),source:'https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade'},
    {id:'clean-recyclebin',risk:'red',methods:[{type:'powershell',value:'Clear-RecycleBin -Confirm',best:true,dangerous:true}],before:D('ריקון הסל מוחק את הפריטים ולא רק מסתיר אותם. בדוק את תוכנו ושחזר קודם קבצים שצריך. הפקודה שומרת את בקשת האישור של PowerShell.','Emptying the bin deletes its contents. Review it and restore needed files first. This command retains the PowerShell confirmation prompt.'),undo:D('אין ביטול רגיל לריקון הסל; שחזור לאחר הריקון אינו מובטח.','There is no normal undo for emptying the bin; later recovery is not guaranteed.'),source:'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-recyclebin'},
    {id:'clean-cipher',risk:'red',methods:[{type:'cmd',value:'cipher /w:C:\\',dangerous:true}],desc:D('דריסה של שטח פנוי בכונן שנבחר; אינה ניקוי שגרתי ואינה שיטה כללית למחיקה מאובטחת של SSD.','Overwrite free space on the selected volume; this is not routine cleanup or a general SSD sanitization method.'),before:D('בדוק היטב את הכונן. פעולה ממושכת שמטרתה לפגוע ביכולת לשחזר קבצים שנמחקו. התוצאה תלויה במדיה ואינה הבטחה למחיקה מלאה של כל עותק.','Verify the drive carefully. This lengthy operation aims to prevent recovery of deleted files. Results depend on the medium and do not guarantee removal of every copy.'),source:cmdDoc('cipher')},
    {id:'sys-shutdown',methods:[{type:'cmd',value:'shutdown /r /t 60',dangerous:true},{type:'cmd',value:'shutdown /a'}],before:D('פקודת האתחול קובעת אתחול בעוד 60 שניות. זמן המתנה אינו תחליף לשמירת עבודה: פקודות כיבוי עם זמן חיובי עלולות לכפות סגירת יישומים. ‎shutdown /a מבטל רק כיבוי ממתין שטרם התחיל.','The restart command schedules a restart in 60 seconds. A delay does not replace saving work: shutdown commands with a positive timeout can force apps closed. shutdown /a only aborts a pending shutdown before it begins.'),source:cmdDoc('shutdown')},
    {id:'sys-taskkill',before:D('הדוגמה מסיימת בכוח תהליכי Chrome ועלולה לאבד עבודה שלא נשמרה. נסה תחילה סגירה רגילה, ואל תעתיק שם תהליך בלי לזהות מה הוא מפעיל.','The example forcibly ends Chrome processes and can lose unsaved work. Try closing normally first; identify a process before targeting it.'),source:cmdDoc('taskkill')},
    {id:'clean-wsreset',desc:D('מאפס את המטמון של Microsoft Store. אינו מאפס או מתקן כל אפליקציה שהותקנה מהחנות.','Reset the Microsoft Store cache. This does not reset or repair every Store-installed application.'),expectedOk:D('החנות עשויה להיפתח לאחר ניקוי המטמון. לאפליקציה אחרת בדוק אפשרות תיקון בהגדרות היישומים.','The Store may open after its cache is cleared. For a different app, check its repair option in app settings.')},
    {id:'sys-msconfig',before:D('כלי לאבחון אתחול ושירותים. אין להשבית שירותים רק מפני ששמם אינו מוכר. השבתה עלולה לפגוע בהגנה, גיבוי, חומרה או התחברות. לניהול תוכנות אתחול רגילות ב-Windows 10/11 העדף את מסך אפליקציות האתחול.','A startup and service diagnostic tool. Do not disable unfamiliar services indiscriminately: protection, backup, hardware or sign-in may break. For routine startup-app management on Windows 10/11, prefer Startup Apps.')},
    {id:'net-arp',desc:D('מציג רשומות ARP במטמון המקומי. זו אינה רשימה מלאה של כל המכשירים ברשת.','Show the local ARP cache. This is not a complete inventory of devices on the network.'),source:cmdDoc('arp')},
    {id:'sys-verifier',before:D('כלי לבדיקת דרייברים שמיועד לאבחון מתקדם ועלול לגרום לקריסות מכוונות. לא מתחילים ממנו בטיפול במחשב איטי. נדרשת תוכנית התאוששות ויכולת להיכנס למצב בטוח.','An advanced driver testing tool that can intentionally trigger crashes. It is not a first step for a slow PC. Have a recovery plan and a way to reach Safe Mode.'),source:'https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/driver-verifier'},
    {id:'disk-health',expectedOk:D('HealthStatus הוא דיווח של שכבת האחסון, לא אבחון מלא. גם Healthy אינו מבטיח שהכונן תקין; התראות, ניתוקים או קבצים פגומים מצריכים גיבוי ובדיקה נוספת.','HealthStatus is a storage-layer report, not a full diagnostic. Healthy does not guarantee a sound drive; alerts, disconnects or corrupt files warrant backup and further checks.')}
  ];
  const newItem=(id,cat,title,desc,type,value,source,extra={})=>({id,cat,title,desc,risk:'green',admin:false,compat:modern,kw:{he:[],en:[]},methods:[{type,value,best:true}],source,...extra});
  const items=[
    newItem('sys-startup-settings','system',D('ניהול אפליקציות אתחול','Manage startup apps'),D('בחירה אילו אפליקציות ייפתחו בכניסה לחשבון.','Choose which apps start when you sign in.'),'run','ms-settings:startupapps',settings,{risk:'yellow',before:D('השבת רק אפליקציה שאתה מזהה. ההגדרה אינה מסירה את התוכנה.','Disable only an app you recognize. This setting does not uninstall it.'),undo:D('הפעל שוב את המתג באותו מסך.','Turn the same toggle back on.')}),
    newItem('sys-update-settings','system',D('פתיחת Windows Update','Open Windows Update'),D('בדיקת מצב העדכונים והיסטוריית ההתקנות.','Inspect update status and installation history.'),'run','ms-settings:windowsupdate',settings),
    newItem('net-proxy-settings','network',D('בדיקת הגדרות Proxy','Inspect proxy settings'),D('בדיקת מתווך הרשת כאשר אפליקציות מסוימות אינן מתחברות.','Inspect the network proxy when some apps cannot connect.'),'run','ms-settings:network-proxy',settings,{before:D('במחשב ארגוני אל תשנה הגדרות שהוגדרו בידי מנהל הרשת.','On a managed PC, do not change settings supplied by your network administrator.')}),
    newItem('disk-storage-settings','disk',D('מה תופס מקום בכונן?','What uses disk space?'),D('צפייה בקטגוריות האחסון לפני בחירה מה לנקות.','Review storage categories before deciding what to clean.'),'run','ms-settings:storagesense',settings,{before:D('פתיחת המסך אינה מוחקת דבר. בדוק את רשימת הקבצים לפני כל פעולת מחיקה בתוך Windows.','Opening this page deletes nothing. Review file selections before any deletion inside Windows.')}),
    newItem('net-help-ipconfig','network',D('עזרה מובנית ל-IPCONFIG','Built-in IPCONFIG help'),D('לימוד האפשרויות הזמינות בגרסת Windows המותקנת.','Learn the options available on the installed Windows version.'),'cmd','ipconfig /?',cmdDoc('ipconfig'),{compat:{xp:'yes',vista:'yes',win7:'yes',...from8}}),
    newItem('sys-powershell-version','system',D('איזו גרסת PowerShell פתוחה?','Which PowerShell version is open?'),D('בודק את המעטפת עצמה, בנפרד מגרסת Windows.','Inspect the shell version separately from the Windows version.'),'powershell','$PSVersionTable', 'https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables', {expectedOk:D('קרא את PSVersion ואת PSEdition אם הוא מופיע. Windows PowerShell 5.1 ו-PowerShell 7 אינם אותה מעטפת.','Read PSVersion and PSEdition when present. Windows PowerShell 5.1 and PowerShell 7 are different shells.')}),
    newItem('sys-location-ps','system',D('באיזו תיקייה אני נמצא?','Which folder am I in?'),D('מציג את המיקום הנוכחי של PowerShell בלי לשנות קבצים.','Show the current PowerShell location without changing files.'),'powershell','Get-Location','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-location'),
    newItem('sys-command-help','system',D('עזרה על פקודת PowerShell','Read PowerShell command help'),D('בדיקת משמעות פרמטרים לפני שימוש בפקודה.','Check parameter meanings before using a command.'),'powershell','Get-Help Get-Process -Examples','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help',{expectedOk:D('התוכן תלוי בעזרה שמותקנת במחשב. אם מופיע מידע חלקי, השתמש במקור הרשמי המקוון.','The content depends on locally installed help. If incomplete, consult the official online documentation.')})
  ];
  const step=(he,en,checkHe,checkEn,cmd='',extra={})=>({do:D(he,en),check:D(checkHe,checkEn),cmd,risk:'green',shell:'cmd',...extra});
  const flow=(id,em,title,steps,source,compat=modern)=>({id,em,cat:'troubleshoot',title,intro:D('בדיקה הדרגתית לפי מה שרואים. אין כאן אבחון אוטומטי של המחשב.','Work through observations step by step. This is not an automatic diagnosis of your PC.'),steps,source,compat});
  const trees=[
    flow('t-net','🌐',D('האינטרנט לא עובד','Internet connection problems'),[
      step('בדוק אם התקלה באתר אחד או בכל החיבורים.','Check whether one site or all connections fail.','נסה אתר אחר ומכשיר אחר באותה רשת. הבדל ביניהם עוזר לצמצם את החיפוש.','Compare another site and another device on the same network to narrow the problem.'),
      step('זהה את המתאם הפעיל ואת שער ברירת המחדל.','Identify the active adapter and default gateway.','כתובת מקומית אינה מוכיחה גישה לראוטר. ‎169.254.x.x עשויה להעיד שלא התקבלה כתובת DHCP.','A local address does not prove router connectivity. 169.254.x.x can indicate no DHCP lease.','ipconfig /all'),
      step('הפרד בין תגובת רשת לפתרון שמות.','Separate network replies from name resolution.','השווה תשובת DNS לגלישה. כישלון ping לבדו אינו מוכיח תקלה אצל הספק: לעיתים ICMP חסום.','Compare DNS answers with browsing. A ping timeout alone does not prove an ISP failure; ICMP may be blocked.','nslookup example.com'),
      step('אם התקלה מקומית, פתח את אבחון הרשת של Windows.','If the issue is local, open Windows network diagnostics.','במחשב ארגוני שמור את ההגדרות ופנה לתמיכה לפני איפוס, החלפת DNS או שינוי VPN.','On a managed PC, record settings and contact support before resetting networking or changing DNS/VPN.','ms-settings:network-status',{shell:'run'})
    ],network),
    flow('t-slow','🐢',D('המחשב איטי','The PC is slow'),[
      step('בדוק עומס נוכחי, בזמן שהתקלה מתרחשת.','Inspect current load while the slowdown occurs.','מיין לפי CPU, זיכרון או דיסק. עומס רגעי בזמן עדכון אינו בהכרח תקלה.','Sort by CPU, memory or disk. A brief load during updates does not necessarily mean a fault.','taskmgr',{shell:'run'}),
      step('בדוק אפליקציות שנפתחות בכניסה.','Review apps that start at sign-in.','השבת רק אפליקציות שאתה מכיר. אל תשבית שירותי אבטחה או דרייברים כחלק מניקוי כללי.','Disable only apps you recognize. Do not disable security services or drivers as general cleanup.','ms-settings:startupapps',{shell:'run',risk:'yellow'}),
      step('בדוק מקום פנוי ופעילות עדכונים.','Check free space and update activity.','עיין באחסון ובמצב Windows Update. אין אחוז פנוי יחיד שמבטיח ביצועים תקינים לכל מחשב.','Review storage and Windows Update. No single free-space percentage guarantees good performance.','ms-settings:storagesense',{shell:'run'}),
      step('אם האיטיות נמשכת, תעד מתי היא מתחילה.','If slowness persists, record when it starts.','רשום תוכנה, משך, עומס, הודעות וחום חריג. אלה מועילים יותר מסריקות תיקון חוזרות בלי ממצא.','Record the app, duration, load, messages and unusual heat rather than repeating repairs without evidence.')
    ],'https://support.microsoft.com/en-us/windows/experience/performance-optimization/tips-to-improve-pc-performance-in-windows'),
    flow('t-errors','🩺',D('בדיקת קבצי מערכת','Check system files'),[
      step('תעד את השגיאה ושמור עבודה.','Record the error and save work.','קבצים פגומים הם אפשרות אחת; אין להסיק שכל קריסה נובעת מהם. פתח CMD כמנהל.','Corrupt files are one possibility, not the explanation for every crash. Open CMD as administrator.'),
      step('תקן את מאגר הרכיבים של Windows.','Repair the Windows component store.','המתן לתוצאה. אם דווח שחסר מקור, רשום את הקוד ופנה להוראות המקור הרשמי.','Wait for the result. If source files are missing, record the code and consult the official procedure.','DISM /Online /Cleanup-Image /RestoreHealth',{admin:true,risk:'yellow'}),
      step('לאחר הצלחת DISM, בדוק את קבצי המערכת.','After DISM succeeds, check system files.','קרא אם לא נמצאו פגמים, אם תוקנו, או אם נותרו פגמים. שמור את ההודעה המדויקת.','Distinguish no corruption, repaired corruption and remaining corruption. Save the exact message.','sfc /scannow',{admin:true,risk:'yellow'}),
      step('בדוק שוב את התקלה המקורית.','Recheck the original problem.','אם הסריקה נקייה והתקלה נמשכת, המשך לאבחון התוכנה, הדרייבר או החומרה.','If the scan is clean but the issue persists, investigate the application, driver or hardware.')
    ],sfc),
    flow('t-update','🔄',D('Windows לא מתעדכן','Windows update problems'),[
      step('קרא את קוד השגיאה ואת מצב העדכון.','Read the error code and update status.','בדוק אם ממתינה הפעלה מחדש ושמור עבודה לפני אישורה.','Check for a pending restart and save work before accepting it.','ms-settings:windowsupdate',{shell:'run'}),
      step('בדוק חיבור, תאריך ומקום פנוי.','Check connectivity, date and free space.','השווה את דרישת המקום שמופיעה בעדכון למקום הפנוי בפועל.','Compare the space requested by the update with actual free space.','ms-settings:storagesense',{shell:'run'}),
      step('השתמש בפותר הבעיות המתאים לגרסת Windows.','Use the troubleshooter for your Windows version.','בגרסאות עדכניות האבחון עשוי לעבור ל-Get Help. אל תמחק אוטומטית תיקיות עדכונים.','Recent versions may route diagnostics through Get Help. Do not automatically delete update folders.'),
      step('אם נשארה שגיאה, חפש אותה במקור הרשמי.','If an error remains, look it up in the official guidance.','ב-Windows 10 בדוק גם מהדורה וזכאות לעדכונים מורחבים; הגדרת גרסה במדריך אינה מעניקה תמיכה.','On Windows 10, also check edition and extended-update eligibility; selecting it here does not provide support.')
    ],'https://support.microsoft.com/en-us/windows/deployment/updates-lifecycle/troubleshoot-problems-updating-windows'),
    flow('t-appcrash','💥',D('אפליקציה קורסת','An application crashes'),[
      step('רשום את שם האפליקציה ואת הודעת השגיאה.','Record the application and error message.','שמור עבודה בתוכנות אחרות. סיום כפוי של התהליך עלול לאבד תוכן שלא נשמר.','Save work in other apps. Forcibly ending the process can lose unsaved content.','taskmgr',{shell:'run'}),
      step('בדוק אירועים בזמן הקריסה.','Inspect events around the crash.','לא כל אזהרה ביומן קשורה לתקלה. חפש את שם היישום ואת השעה המתאימה.','Not every warning is related. Look for the application name and matching time.','eventvwr.msc',{shell:'run'}),
      step('בדוק עדכון ואפשרות Repair של היישום.','Check updates and the app’s Repair option.','Reset והסרה עשויים למחוק נתוני אפליקציה. גבה קודם ובדוק הוראות של היצרן.','Reset and uninstall can remove app data. Back up first and check the publisher’s instructions.'),
      step('אם דווקא Microsoft Store תקועה, בדוק את המטמון שלה.','If Microsoft Store itself is stuck, check its cache.','wsreset מטפל במטמון החנות בלבד; אינו תיקון כללי לכל תוכנות החנות.','wsreset addresses the Store cache; it is not a general repair for every Store app.','wsreset',{shell:'run',risk:'yellow'})
    ],'https://support.microsoft.com/en-us/windows/apps/repair-apps-and-programs-in-windows'),
    flow('t-sound','🔊',D('אין קול','No sound'),[
      step('בדוק התקן פלט, השתקה ועוצמת האפליקציה.','Check the output device, mute and app volume.','בדוק שלא נבחר מסך HDMI במקום אוזניות. נסה קובץ אחר.','Check whether HDMI was selected instead of headphones. Try another audio file.','mmsys.cpl',{shell:'run'}),
      step('בדוק חיבור והתקן נוסף.','Check the connection and another device.','החלפת יציאה או אוזניות עוזרת להפריד בין בעיית ציוד להגדרה.','Another port or headset helps distinguish equipment from a setting.'),
      step('הפעל את אבחון השמע של Windows.','Run Windows audio diagnostics.','מיקום האבחון משתנה בין גרסאות; השתמש בהגדרות השמע או ב-Get Help.','The location varies by version; use Sound settings or Get Help.','ms-settings:sound',{shell:'run'}),
      step('אם התקלה החלה אחרי דרייבר, בדוק את ההיסטוריה.','If it started after a driver change, inspect that change.','אל תסיר דרייברים רבים יחד. בדוק את הוראות יצרן המחשב.','Do not remove multiple drivers together. Check the PC manufacturer’s guidance.','devmgmt.msc',{shell:'run'})
    ],'https://support.microsoft.com/en-us/windows/hardware/audio/fix-sound-or-audio-problems-in-windows'),
    flow('t-printer','🖨️',D('המדפסת לא מדפיסה','Printer will not print'),[
      step('בדוק מתח, נייר וחיבור.','Check power, paper and connection.','בהדפסה דרך רשת ודא שנבחרה המדפסת הנכונה ושאין הודעה בצג שלה.','For network printing, check the selected printer and its display.'),
      step('בדוק את תור ההדפסה.','Inspect the print queue.','ביטול משימה מסיר את בקשת ההדפסה; שמור את המסמך כדי לשלוח שוב.','Canceling removes the print request; keep the document so it can be resubmitted.','ms-settings:printers',{shell:'run'}),
      step('השתמש באבחון מדפסות של Windows.','Use Windows printer diagnostics.','אתחול Spooler לבדו לא תמיד מוחק משימות תקועות. אל תמחק קבצי מערכת כחלק מניסוי.','Restarting Spooler alone does not always clear stuck jobs. Do not delete system files as an experiment.'),
      step('אם הבעיה נשארה, רשום דגם וקוד שגיאה.','If it persists, record model and error code.','פנה להוראות היצרן עם פרטי החיבור והתוצאה של הדפסת דף בדיקה.','Consult the manufacturer with connection details and the test-page result.')
    ],'https://support.microsoft.com/en-us/windows/hardware/printer/fix-printer-connection-and-printing-problems-in-windows')
  ];
  window.PCG_CONTENT={patches,items,trees,reviewed:'2026-09-22'};
})();
